# Generated by Django 2.0.4 on 2018-05-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
