# Generated by Django 2.0.4 on 2018-05-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exex', '0002_auto_20180519_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='dob',
        ),
    ]
