# Generated by Django 2.0.4 on 2018-05-19 13:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exex', '0003_remove_author_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=250)),
                ('subtitle', models.CharField(blank=True, default='Subtitle', max_length=500)),
                ('summary', models.CharField(blank=True, default='summary', max_length=1500)),
                ('latitude', models.DecimalField(decimal_places=8, default='', max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, default='', max_digits=12)),
                ('place', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=50000)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('article_image', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exex.author')),
            ],
        ),
    ]
